### ISSUE TITLE
R CMD check fails due to unit test issue

### ISSUE THREAD

**Issue by GegznaV** [bryanhanson/roxut#5] opened 2021-08-16 22:10 UTC
See https://github.com/r-hyperspec/hySpc.read.spe/issues/43 Please confirm, if you can reproduce the issue. ⚠️ If yes, a hotfix 🔧  in CRAN version is needed.

**Comment by bryanhanson** [comment] 2021-08-17 03:23
Thanks for this report.  This is not a problem on Ubuntu or Mac OS, but clearly it's a problem for Windows.  I'll need your help to fix this as I don't have an effective way to test on Windows.

The problem is in `roclet_output.roclet_tests()`, at these lines:
```
    # extract the test contents
    # next line is simply the tests
    # tests <- sub("(\\[.*\\.R:[0-9]+\\])(.*)", "\\2", results[[framework]])
    # next line gets the tests and the line number where the test begins in the file (thx to CB)
    tests <- sub("\\[.*/([^/]+\\.R:[0-9]+)\\](.*)", "\n# test found in \\1 (file:line)\n\\2", results[[framework]])
```
The 2nd instance of `tests` is the problem.  CB made this regex to extract not only the test but also the line numbers.  The original `tests` is commented out earlier.  I suggest you comment out the new version and try the old version, and see if that causes a problem on Windows.  If the old code works, there are two options: leave the old code and go w/o the line numbers, or fix the regex in the new code so that it also works with Windows.

Now, how do you know if the changes work?  There are 2 ways. One is to make the change, build, check and install locally, and use it in another package (I guess `hySpc.read.spe`).

The second way is to use the internal `roxut` test mechanism.  The way `roxut` tests itself if that it builds a package contained within the test suite, and then one checks the structure of that test package and in particular the unit test files.  Details in the next paragraph.

In `roxut/inst/tinytest` you will see a file `test_roxutTestPkg.R`.  This file basically writes a report into the log file as it checks the test package.  In that file you'll see a line `    system2("cp", "-r . ~/Desktop/tempdir") # good for troubleshooting
`  If you change this line so that it writes to a suitable place on your computer, then build, check and install `roxut` the entire test package will be written to the location you specify.  Then you can take a look at the unit tests, both `tinytest` and `testthat` and see what was written in the file.  Of course, you'll want to comment out this line when you are done.

Please give one of these a try and let me know what you find out.

**Comment by bryanhanson** [comment] 2021-08-17 18:31
Another possibility: disable the problematic line just for Windows by detecting the OS.

**Comment by GegznaV** [comment] 2021-08-17 21:15
What is the expected result of `results[[framework]]` in `roclet_output.roclet_tests()`?

**Comment by GegznaV** [comment] 2021-08-17 21:31
OK I think, I know what is the issue: the default file path separator on windows is `\`, on Unix-based OS'es, is `/`. But Windows accept `/` as well.

The lines, e.g.:
```r
regularized_path <- gsub("\\\\", "/", windows_path)
```
used in the right place can do the job.

**Comment by GegznaV** [comment] 2021-08-17 21:34
Regex
```r
tests <- sub("\\[.*[/\\\\]([^/\\\\]+\\.R:[0-9]+)\\](.*)", "\n# test found in \\1 (file:line)\n\\2", results[[framework]])
```
may also work but it is less readable.

**Comment by bryanhanson** [comment] 2021-08-17 22:01
@GegznaV What does the following function give for your machine?
```
get_os <- function(){
  sysinf <- Sys.info()
  if (!is.null(sysinf)){
    os <- sysinf['sysname']
    if (os == 'Darwin')
      os <- "osx"
  } else { ## mystery machine
    os <- .Platform$OS.type
    if (grepl("^darwin", R.version$os))
      os <- "osx"
    if (grepl("linux-gnu", R.version$os))
      os <- "linux"
  }
  tolower(os)
}
```

**Comment by bryanhanson** [comment] 2021-08-19 18:19
Trying to track this down.  `roxut` passes on Windows just fine at win-builder, however if one digs into the logs a bit (which are hard to read), I think I see the offending line in this [file](https://win-builder.r-project.org/DU9Fd2NJPsEL/examples_and_tests/roxut-Ex_i386.Rout).

**Comment by bryanhanson** [comment] 2021-08-21 16:07
Fixed via https://github.com/bryanhanson/roxut/commit/350a49e69b639af3243fdade70cae36c7fdce5c2 Thanks to VG for testing on Windows 10.

**Closed as completed by bryanhanson** 2021-08-21 16:07 UTC
