### ISSUE TITLE
Mutliple @tests blocks in one file overwrite each other

### ISSUE THREAD

**Issue by cbeleites** [bryanhanson/roxut#1] opened 2021-08-05 13:07 UTC
... so only the last such block actually appears in `test_filename.R`.

This happens in `roclet_output.roclet_tests()`

possible solutions:

-  output multiple files `test_filename.R`, test_filename-1.R`, etc.:
  ```r
  # extract the original short filenames
  fn <- sub("\\[(.*)\\.R:[0-9]+\\](.*)", "\\1", results[[framework]])
  fn <- basename(fn)
  fn <- make.unique(fn, "-")
  fn <- paste0(fn, ".R")
  ```
- paste the blocks for each file, so that one longer  `test_filename.R` results

**Comment by cbeleites** [comment] 2021-08-05 13:09
[testFile-multiple-functions.R.txt](https://github.com/bryanhanson/roxut/files/6938835/testFile-multiple-functions.R.txt)

(github doesn't accept .R files)

**Comment by bryanhanson** [comment] 2021-08-05 13:28
Alright, good catch, I shall take a look.  I don't think this happens in another place I use it but maybe I missed it.  Thanks for the suggestions.

**Comment by bryanhanson** [comment] 2021-08-05 13:41
OK, the other package where I am using it, I use `tinytest` and there's no problem.  On the other hand, things are not wrapped in `test_that` in `tinytest` so that's probably why the problem is limited to `testthat`.  A clue at least.

**Comment by bryanhanson** [comment] 2021-08-05 14:04
OK, I'm catching up here.  Do you see this problem in `hySpc.read.jdx`?  When I build and check locally the test file is produced fine.  Having looked around and re-read your report a couple of times, I now think you are telling me that the testing infrastructure in `roxut` itself has this problem.  Is that correct?

**Comment by cbeleites** [comment] 2021-08-05 16:12
Yes - I thought I'd get familiar with **roxut** by using it for a totally different package I just start, and also to give **tinytest** a try. So I actually see this with **tinytest**.

What happens is that `writeUT()` writes the first test block into a `test_filename.R`-file and when another test block is in the results list with the same `filename`, `test_filename.R` gets overwritten. (Instead of appending?)  
I confirmed that this happens by `debug(roxut:::roclet_output.roclet_tests)` and watching the contents of the test file while manually looping over the `fn[i]`/`tests[i]` combination.

I can work around this by keeping strictly to one-function-one-file. 
I ran into this when setting up a `pca_lda.R` for PCA-LDA models where I put the generic `pca_lda()` as well as some S3 methods (`pca_lda.default()`, `pca_lda.formula()`).  

---

**hySpc.read.jdx** has only a single `@tests` block in the whole package, so this issue doesn't occur there.

**Comment by bryanhanson** [comment] 2021-08-05 16:18
I understand— thanks. Not sure if one should support multiple @tests, but at the minimum I can improve the docs.

**Comment by bryanhanson** [comment] 2021-08-05 16:18
And of course I need to fix the internal testing

**Comment by cbeleites** [comment] 2021-08-05 16:25
Since one can have multiple roxygen blocks in one file without problems (and even getting them to refer to the same `@rdname`) I did expect this to work.

Throwing at least a warning in case of `any(duplicated(fn))` would be a friendly move, I think. 

---

In case you decide for supporting multiple test blocks, I can put together a PR - but would need to know what solution you prefer.
(That is, with the exception of your package test, I did not dig sufficiently into that voodoo... )

**Comment by bryanhanson** [comment] 2021-08-05 16:35
Let me spend some more time with it this weekend— I’m traveling later today.

**Comment by bryanhanson** [comment] 2021-08-08 20:03
Fixed with a slight variation on your approach.  Thanks a bunch! Can you test the `issue#1` branch please? It seems to work locally.

**Comment by cbeleites** [comment] 2021-08-09 14:43
Thank you! Works for me :-)

**Comment by bryanhanson** [comment] 2021-08-09 14:46
Alright, VG has noticed something inconsistent with file names so I shall address that and then get things ready for CRAN.

Closed via https://github.com/bryanhanson/roxut/commit/ac820785755f58d27b72fcbda1419033a76b66d9

**Closed as completed by bryanhanson** 2021-08-09 14:46 UTC
